<a href="https://colab.research.google.com/github/Rinisha160391/tensorflow/blob/main/tensorflow_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.12.0


#Initialize a tensor

tensor is an nD array(
vector - 1D tensor,
matrix - 2D tensor)

In [15]:
x=tf.constant(4)
print(x)
y=tf.constant(5,shape=(2,2))
print(y)
z=tf.constant([[1,2,3],[4,5,6]])
print(z)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [22]:
print(tf.ones((3,3)))
print(tf.zeros((4,4)))
print(tf.eye((3))) #identical matrix

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [25]:
print(tf.random.normal((3,3),mean=0,stddev=1))
print(tf.random.uniform((3,3),minval=1,maxval=5))
print(tf.range(10))

tf.Tensor(
[[ 1.177441    1.719767    1.1337433 ]
 [ 2.503924   -1.4244683   0.24762847]
 [-0.7016131  -0.04552308  0.8359228 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4.4980235 2.810925  2.4090233]
 [3.1698475 2.0578904 3.1582212]
 [3.600151  4.3941135 1.086031 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [28]:
x=tf.range(10)
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])>

#Mathematical operations

In [36]:
x=tf.constant([4,5,6])
y=tf.constant([1,2,3])
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.multiply(x,y))
print(tf.divide(x,y))
print(tf.tensordot(x,y,axes=1))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)
tf.Tensor(32, shape=(), dtype=int32)


In [41]:
x=tf.random.normal((3,3))
y=tf.random.normal((3,2))
print(tf.matmul(x,y))

tf.Tensor(
[[ 1.3156625  -2.1346502 ]
 [-0.84840727  0.9630437 ]
 [-1.2156175   2.4421413 ]], shape=(3, 2), dtype=float32)


In [48]:
print(x[1,:]) #indexing
print(tf.reshape(x,(9)))
print(tf.transpose(x))

tf.Tensor([ 0.5360431  -0.40060416 -2.4180079 ], shape=(3,), dtype=float32)
tf.Tensor(
[-0.6347146  -0.9841645  -0.05858905  0.5360431  -0.40060416 -2.4180079
  1.0044726   0.802922   -0.54611355], shape=(9,), dtype=float32)
tf.Tensor(
[[-0.6347146   0.5360431   1.0044726 ]
 [-0.9841645  -0.40060416  0.802922  ]
 [-0.05858905 -2.4180079  -0.54611355]], shape=(3, 3), dtype=float32)
